### PR TITLE
Added SPC7110 chip support

### PR DESCRIPTION
**Pull request by Nukotan**
Add support for SPC7110 chip.

### CODE REVIEW

**Comment by 173210** [comment]
Thank you!
Some person wanted it.
They will be glad to get it!

**Comment by 173210** [comment]
Unfortunately, I tested it but it failed.
I got this error when start sound thread : 0x80020190
It means memory shortage.
Didn't you get this error?

**Comment by Nukotan** [comment]
Thanks for merging :)

Sorry, I have only the old PSP :(
I did the test results, no problem.

Some Info:
Compiler: Minimalist PSPSDK for Windows v.0.11.2r3
Test: PSP-1000, CFW6.60 ME-1.8

**Comment by 173210** [comment]
It won't still work.
Could you give me your binary?

**Comment by Nukotan** [comment]
Okay.
Upload to https://dl.dropboxusercontent.com/u/102023246/130603_s9xTYLmecm_mod_spc7110.7z

**Comment by 173210** [comment]
It worked.
I'll try to compile a working binary...

**Comment by 173210** [comment]
Compile succeed!
Thank you for your support!

**Comment by Nukotan** [comment]
Graphic breaks down at the FEoEZ opening demo.

Quick fix:
https://gist.github.com/Nukotan/b3576c77a59524f43939

Thanks.

**Comment by 173210** [comment]
Your fix works well.
Thanks.

**Pull request merged**
